### PR TITLE
【bug】修复迁移目的位置错误bug

### PR DESCRIPTION
**Pull request by zengjiwen**
1. 修复迁移目的位置错误bug
2. 代码优化

### CODE REVIEW

**Comment by zengjiwen** [comment]
@xiaonanln

**Review by xiaonanln — APPROVED** [review]
LGTM :+1:

**Comment by xiaonanln** [comment]
> 1. 修复迁移目的位置错误bug
> 2. 代码优化

Thanks for the fix.

**Comment by xiaonanln** [comment]
Please fix the build errors. I would recommend to not include unrelated changes. @zengjiwen

**Comment by zengjiwen** [comment]
> Please fix the build errors. I would recommend to not include unrelated changes. @zengjiwen

ok

**Comment by zengjiwen** [comment]
I'll fix the migrate test err later.

**Pull request merged**
